# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  lando-api:
    build:
      context: ../lando-api/
      dockerfile: ./Dockerfile
    image: suite_lando-api
    environment:
      PORT: 9000
      VERSION_PATH: /version.json

    volumes:
      - ../lando-api/:/app
      - ../lando-api/docker/dev-version.json:/version.json
      - ../lando-api/migrations/:/migrations/
